repository_type: pipeline

nf_core_version: 3.5.2

lint:
  logo: False

template:
  org: nf-core
  name: funcprofiler
  description: Read-based functional profiling of microbiome sequencing data
  author: Nick Waters
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
